# -*- coding: utf-8 -*-
# vim: ft=yaml
---
driver:
  name: linode

provisioner:
  name: salt_solo
  formula: ${formula_name}
  state_top:
    base:
      "*":
        - ${formula_name}

platforms:
  - name: debian_jessie

suites:
  - name: default

  - name: custom
    provisioner:
      pillars-from-files:
        ${formula_name}.sls: pillar-custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - ${formula_name}
